# Generated by Django 4.1 on 2022-09-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_employee_company_employee_departament_and_more'),
        ('extra_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratime',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employes.employee'),
        ),
    ]
