# Generated by Django 4.1 on 2022-09-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0001_initial'),
        ('employes', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.ManyToManyField(blank=True, null=True, to='departaments.departament'),
        ),
    ]
