# Generated by Django 4.1 on 2022-09-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0001_initial'),
        ('employes', '0007_employee_city_employee_country_employee_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.ManyToManyField(blank=True, to='departaments.departament'),
        ),
    ]
